get:
  summary: Get public settings.
  operationId: getPublicSettings
  tags: [PublicSettings]
  responses:
    '200':
      description: List of all association settings.
      content:
        application/json:
          schema:
            $ref: '../components/settings.yml#/components/schemas/PublicSettingsResponse'