get:
  summary: Get all settings.
  operationId: getAllSettings
  tags: [Settings]
  responses:
    '200':
      description: List of all association settings.
      content:
        application/json:
          schema:
            $ref: '../components/settings.yml#/components/schemas/SettingsResponse'