components:
  parameters:
    sortParam:
      name: sort
      description: Sorting to apply.
      in: query
      style: form
      explode: true
      required: false
      schema:
        type: array
        items:
          type: string
          pattern: '^(code|type)\|(asc|desc)$'
          example: code|asc
  schemas:
    Setting:
      type: object
      required: [type, code, value]
      properties:
        type:
          type: string
          description: Type of the setting.
        code:
          type: string
          description: Unique code identifying the setting.
        value:
          type: string
          description: Value of the setting.
    SettingChange:
      type: object
      required: [value]
      properties:
        value:
          type: string
          description: Updated value for the setting.
    PublicSettings:
      type: object
      properties:
        mapCode:
          type: string
        calendarCode:
          type: string
    PublicSettingsResponse:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/PublicSettings'
    SettingsResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Setting'
    SettingResponse:
      type: object
      properties:
        content:
          $ref: '#/components/schemas/Setting'